# BO params
num_opt_samples: 50
num_folds: 3
num_cpus: 4
num_gpus: 1

# Points to evaluate
lr: 0.001
weight_decay: 0.00005

# Else
output_dir: ./output/
hydra:
  run:
    dir: ${output_dir}
  job_logging:
    handlers:
      file:
        mode: w